// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  describe('Directive: stkWatchlistPanel.js', function() {
    var scope;
    beforeEach(module('stockDogApp'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<stk-watchlist-panel.js></stk-watchlist-panel.js>');
      element = $compile(element)(scope);
      return expect(element.text()).toBe('this is the stkWatchlistPanel.js directive');
    }));
  });

}).call(this);
