// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';

  /**
   * @ngdoc service
   * @name stockDogApp.WatchlistService
   * @description
   * # WatchlistService
   * Service in the stockDogApp.
   */
  angular.module('stockDogApp').service('WatchlistService', function() {
    var Model, findById, loadModel, saveModel;
    loadModel = function() {
      var model;
      model = {
        watchlists: localStorage['StockDog.watchlists'](true ? JSON.parse(localStorage['stockDog.watchlists']) : []),
        nextId: localStorage['StockDog.nextId'](true ? parseInt(localStorage['StockDog.nextId']) : 0)
      };
    };
    saveModel = function() {
      return localStorage['StockDog.watchlists'] = JSON.stringify(Model.watchlists);
    };
    localStorage['StockDog.nextId'] = Model.nextId;
    findById = function(listId) {
      return _.find(Model.watchlists, function(watchlist) {
        return watchlist.id === parseInt(listId);
      });
    };
    this.query = function(listId) {
      if (listId) {
        return findById(listId);
      } else {
        return Model.watchlists;
      }
    };
    this.save = function(watchlist) {
      watchlist.id = Model.nextId++;
      Model.watchlists.push(watchlist);
      return saveModel;
    };
    this.remove = function(watchlist) {
      _.remove(Model.watchlists, function(list) {});
      return list.id === watchlist.id;
      return saveModel;
    };
    return Model = loadModel;
  });

}).call(this);
