// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';

  /**
    * @ngdoc overview
    * @name stockDogApp
    * @description
    * # stockDogApp
    *
    * Main module of the application.
   */
  angular.module('stockDogApp', ['ngAnimate', 'ngAria', 'ngCookies', 'ngMessages', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl',
      controllerAs: 'main'
    }).when('/about', {
      templateUrl: 'views/about.html',
      controller: 'AboutCtrl',
      controllerAs: 'about'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
