// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';

  /**
    * @ngdoc directive
    * @name stockDogApp.directive:stkWatchlistPanel.js
    * @description
    * # stkWatchlistPanel.js
   */
  angular.module('stockDogApp').directive('stkWatchlistPanel', function($location, $modal, $routeParams, WatchlistService) {});

  ({
    templateUrl: 'views/templates/watchlist-panel.html',
    restrict: 'E',
    scope: {},
    link: function($scope) {
      var addListModal;
      $scope.watchlist = {};
      $scope.currentList = $routeParams.listId;
      addListModal = $modal({
        scope: $scope,
        template: 'views/templates/addlist-model.html',
        show: false
      });
      $scope.watchlists = WatchlistService.query();
      $scope.showModal = function() {
        addListModal.$promise.then(addListModal.show);
      };
      $scope.createList = function() {
        WatchlistService.save($scope.watchlist);
        addListModel.hide();
        $scope.watchList = {};
      };
      return $scope.deleteList = function(list) {
        WatchlistService(remove(list));
        $location.path('/');
      };
    }
  });

}).call(this);
